name: slicing_ui
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.0
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/apple.png
    - assets/arrow.png
    - assets/burger.png
    - assets/chat.png
    - assets/delivery.jpg
    - assets/fast food.png
    - assets/Group 12 (1).png
    - assets/Group 12.png
    - assets/home.png
    - assets/kue kue.jpg
    - assets/more.png
    - assets/orange-juice.png
    - assets/plus.png
    - assets/promo.png
    - assets/shopping-bag.png
    - assets/store.png
    - assets/vegetables.png
    - assets/wallet.png
    - assets/man.png
    - assets/loading.json